### ISSUE TITLE
docker-compose-ollama-gpu.yaml configuration failing

### ISSUE THREAD

**Issue by mdrewry** [valiantlynx/ollama-docker#1]
When I attempt to run the docker compose file with gpu support, ollama exits with the following error:

> Error: unknown flag: --gpus

**Comment by valiantlynx** [comment]
ill check it out. and fix that

**Comment by valiantlynx** [comment]
i've merged the fix. at least for nvidia gpus. the fix is similar for other gpus but of course you have to read your gpus docs if it conflicts.
