### ISSUE TITLE
Changing the 11434 as the system port default

### ISSUE THREAD

**Issue by sandeepzgk** [valiantlynx/ollama-docker#8]
The use of port 11434 conflicts with the default local installation of ollama, it might be better to map the container to a different port so that it does not conflict with any existing ollama installation

**To Reproduce**
1. Install Ollama on the base computer
2. Start docker compose for ollama-docker

**Expected behavior**
It should work as expected. Instead it gives a port error given that port 11434 is used on the system by ollama 

**Suggested Fix **
Map a different port in docker-compose (gpu and non gpu version) with 
      - 11435:11434
      - Update the environment variable to use 11435 
      - it could be literally any other port

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 
 - Browser NA

**Comment by valiantlynx** [comment]
i agree. i didnt think about people who already a have an installation of ollama. ill do that

**Comment by valiantlynx** [comment]
ive thought about it and  if someone already has ollama running, they could just comment out ollama. another option would be to  have a bash script that asks if you have ollama already and if you have a gpu? 

it doesnt make to have two ollama running, and it doesnt affect the ollama installation if you already have it just uses it. 
what do you think?

**Comment by valiantlynx** [comment]
now it should be easy as you can have multiple ollama hosts and it will be load balanced if you want
